from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
MODEL_DIR = BASE_DIR / "models"

MODEL_PATH = MODEL_DIR / "bisindo_model_final.keras"
CLASS_NAMES_PATH = MODEL_DIR / "class_names.json"
HAND_LANDMARKER_PATH = MODEL_DIR / "hand_landmarker.task"




INPUT_SIZE = 126
NUM_HAND_FEATURES = 63


CONFIDENCE_THRESHOLD = 0.80



MAX_NUM_HANDS = 2

MIN_HAND_DETECTION_CONFIDENCE = 0.60
MIN_HAND_PRESENCE_CONFIDENCE = 0.60
MIN_TRACKING_CONFIDENCE = 0.60



PREDICTION_HISTORY_SIZE = 8


MIN_STABLE_COUNT = 6





RELEASE_FRAME_COUNT = 8


MAX_SENTENCE_LENGTH = 100




CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

WINDOW_NAME = "BISINDO AI Translator"
ESC_KEY = 27




COLOR_BACKGROUND = (25, 25, 25)
COLOR_PANEL = (40, 40, 40)
COLOR_TEXT = (255, 255, 255)

COLOR_SUCCESS = (80, 220, 120)
COLOR_WARNING = (0, 210, 255)
COLOR_ERROR = (80, 80, 255)
COLOR_ACCENT = (255, 180, 60)

AUTO_SPEAK_DELAY_SECONDS = 2.0